Adjust actions

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -1,14 +1,26 @@
 on: push
-name: Code checks
+name: Code Checks
 jobs:
   staticAnalysis:
     name: Static Analysis
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@master
-    - name: Static Analysis
-      uses: ./.github/actions/static-analysis
-    - name: Check CHANGELOG
-      uses: ./.github/actions/bin/diff-check
+    - uses: ./.github/actions/static-analysis
+  checkChangelog:
+    name: Check CHANGELOG
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
       with:
-        args: CHANGELOG.md
+    - run: |
+        git fetch origin
+        if sh -c "git diff origin/develop --exit-code $var"; then
+            echo "$var wasn't changed, failing!"
+            exit 255 
+        else
+            exit_code=$?
+            echo "$var was changed, passing!"
+            exit 0
+        fi
+
